---
title: "Additional test cases"
output: 
  github_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, 
                      fig.width = 10, fig.height = 6)
```

## Full COMPAS data

```{r}
library(seeBias)
# Load example data
data("compas")
head(compas)
table(compas$Two_yr_Recidivism, compas$Ethnicity)
# Not sensible to analyse Asian and Native American as separate categories due
# to insufficient observations. Combine into Other.
compas$Ethnicity <- ifelse(compas$Ethnicity %in% c("Asian", "Native_American"),
                           "Other", as.character(compas$Ethnicity))
compas$Ethnicity <- ifelse(compas$Ethnicity == "African_American",
                           "African American", as.character(compas$Ethnicity))
table(compas$Two_yr_Recidivism, compas$Ethnicity)
m <- glm(Two_yr_Recidivism ~ ., data = compas, family = "binomial")
# Extracted predicted risk and observations from test data.
# If not specified, the best threshold in ROC analysis is used.
x <- evaluate_prediction_prob(
  y_pred = predict(m, newdata = compas, type = "response"), 
  y_obs = compas$Two_yr_Recidivism, y_pos = "1",
  sens_var = compas$Ethnicity, sens_var_ref = "Caucasian"
)
table(x$input$data$sens_var, x$input$data$y_obs)
x_plots <- plot(x)
```

```{r results='asis'}
summary(x)
```

### Individual plots

```{r}
x_plots$`Performance metrics`
```

```{r, fig.width=7, fig.height=4}
x_plots$`ROC curves`
x_plots$`Calibration in the large`
x_plots$`Calibration curves`
x_plots$`Boxplot of predictions`
x_plots$`Number needed for true positive`
x_plots$`Number needed for true negative`
```

User define color scheme:

```{r}
x_plots$`Performance metrics` + ggsci::scale_fill_npg()
```

```{r, fig.width=7, fig.height=4}
x_plots$`ROC curves` + ggsci::scale_color_npg()
x_plots$`Calibration in the large` + ggsci::scale_fill_npg()
x_plots$`Calibration curves` + ggsci::scale_color_npg()
x_plots$`Boxplot of predictions` + ggsci::scale_color_npg()
x_plots$`Number needed for true positive` + ggsci::scale_color_npg()
x_plots$`Number needed for true negative` + ggsci::scale_color_npg()
```

## Multiple sensitive variables

```{r, fig.width=10, fig.height=6}
x2 <- evaluate_prediction_prob(
  y_pred = predict(m, newdata = compas, type = "response"), 
  y_obs = compas$Two_yr_Recidivism, y_pos = "1",
  sens_var = cbind(as.character(compas$Ethnicity), as.character(compas$Sex)), 
  sens_var_ref = c("Caucasian", "Male")
)
table(x2$input$data$sens_var, x2$input$data$y_obs)
x_plots2 <- plot(x2, print_statistics = FALSE)
```

```{r results='asis'}
summary(x2)
```

```{r, fig.width=7, fig.height=4}
x_plots2$`ROC curves`
x_plots2$`Calibration in the large`
x_plots2$`Calibration curves`
x_plots2$`Boxplot of predictions`
x_plots2$`Number needed for true positive`
x_plots2$`Number needed for true negative`
```

## Specify predicted scores

```{r, fig.width=10, fig.height=6}
x3 <- evaluate_prediction_score(
  y_pred = predict(m, newdata = compas), 
  y_obs = compas$Two_yr_Recidivism, y_pos = "1",
  sens_var = cbind(as.character(compas$Ethnicity), as.character(compas$Sex)), 
  sens_var_ref = c("Caucasian", "Male")
)
table(x3$input$data$sens_var, x3$input$data$y_obs)
x_plots3 <- plot(x3, print_statistics = FALSE)
```

```{r results='asis'}
summary(x3)
```

```{r, fig.width=7, fig.height=4}
x_plots3$`ROC curves`
x_plots3$`Calibration in the large`
x_plots3$`Calibration curves`
x_plots3$`Boxplot of predictions`
x_plots3$`Number needed for true positive`
x_plots3$`Number needed for true negative`
```
